[SymForce] Remove intel macos wheels
llvmlite stopped building intel macos wheels, and the llvmlite build
doesn't work out-of-the-box on cibuildwheel on macos-15-intel so this
fails unless we fix it, and I don't want to fix it.  We could instead
use our pinned dependencies for the wheel tests, but that's both
slightly annoying (requires handling skymarshal and symforce-sym) and
just kicks the can down the road a little

```
Building wheel for llvmlite (setup.py): started
Building wheel for llvmlite (setup.py): finished with status 'error'
error: subprocess-exited-with-error

× python setup.py bdist_wheel did not run successfully.
│ exit code: 1
╰─> [44 lines of output]
    /private/var/folders/kk/yc0qf4694xl1_d6sqg40_2sr0000gn/T/cibw-run-otwsvrxz/cp310-macosx_x86_64/venv-test-x86_64/lib/python3.10/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'license_expression'
      warnings.warn(msg)
    running bdist_wheel
    /private/var/folders/kk/yc0qf4694xl1_d6sqg40_2sr0000gn/T/cibw-run-otwsvrxz/cp310-macosx_x86_64/venv-test-x86_64/bin/python /private/var/folders/kk/yc0qf4694xl1_d6sqg40_2sr0000gn/T/pip-install-guqqjwq5/llvmlite_a4d3f0febd1c481cb36149720915be0e/ffi/build.py
    -- The C compiler identification is AppleClang 17.0.0.17000013
    -- The CXX compiler identification is AppleClang 17.0.0.17000013
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at CMakeLists.txt:21 (find_package):
      Could not find a package configuration file provided by "LLVM" with any of
      the following names:

        LLVMConfig.cmake
        llvm-config.cmake

      Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
      "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
      provides a separate development package or SDK, be sure it has been
      installed.

    -- Configuring incomplete, errors occurred!
    Running: cmake -G Unix Makefiles /private/var/folders/kk/yc0qf4694xl1_d6sqg40_2sr0000gn/T/pip-install-guqqjwq5/llvmlite_a4d3f0febd1c481cb36149720915be0e/ffi
    Traceback (most recent call last):
      File "/private/var/folders/kk/yc0qf4694xl1_d6sqg40_2sr0000gn/T/pip-install-guqqjwq5/llvmlite_a4d3f0febd1c481cb36149720915be0e/ffi/build.py", line 209, in <module>
        main()
      File "/private/var/folders/kk/yc0qf4694xl1_d6sqg40_2sr0000gn/T/pip-install-guqqjwq5/llvmlite_a4d3f0febd1c481cb36149720915be0e/ffi/build.py", line 203, in main
        main_posix('.dylib')
      File "/private/var/folders/kk/yc0qf4694xl1_d6sqg40_2sr0000gn/T/pip-install-guqqjwq5/llvmlite_a4d3f0febd1c481cb36149720915be0e/ffi/build.py", line 189, in main_posix
        try_cmake(here_dir, build_dir, generator)
      File "/private/var/folders/kk/yc0qf4694xl1_d6sqg40_2sr0000gn/T/pip-install-guqqjwq5/llvmlite_a4d3f0febd1c481cb36149720915be0e/ffi/build.py", line 127, in try_cmake
        subprocess.check_call(args)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '-G', 'Unix Makefiles', '/private/var/folders/kk/yc0qf4694xl1_d6sqg40_2sr0000gn/T/pip-install-guqqjwq5/llvmlite_a4d3f0febd1c481cb36149720915be0e/ffi']' returned non-zero exit status 1.
    error: command '/private/var/folders/kk/yc0qf4694xl1_d6sqg40_2sr0000gn/T/cibw-run-otwsvrxz/cp310-macosx_x86_64/venv-test-x86_64/bin/python' failed with exit code 1
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for llvmlite
Running setup.py clean for llvmlite
```

Topic: sf-intel-macos
Assignees: nathan
GitOrigin-RevId: e1ceaec41dcc021c6ac11db4dacd026ee6d11b81