[SymForce] Pull in the latest tl::optional
When compiling with -Werror=extra, the symforce build fails with:

_deps/tl_optional-src/include/tl/optional.hpp:455:3: error: base class 'struct tl::detail::optional_operations_base<sym::Linearization<double> >' should be explicitly initialized in the copy constructor [-Werror=extra]
  455 |   optional_copy_base(const optional_copy_base &rhs) {
      |   ^~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

This was fixed upstream in TartanLlama/optional#45, which is not yet
in any tagged release. Bump the version of tl::optional used by
symforce to pull in this fix.

Signed-off-by: Brian Kubisiak
GitOrigin-RevId: b5b0802e8da8e2099980cc5a60674c9365367ac3