[SymForce] Fix new_symbol on py3.10+
Fixes a bug introduced in `[SymForce] More docs`:

```python
>>> import symforce.symbolic as sf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "symforce/symforce/symbolic.py", line 27, in <module>
    from symforce.internal.symbolic import *
  File "symforce/symforce/internal/symbolic.py", line 330, in <module>
    def new_symbol(
  File "/home/aaron/miniconda3/envs/symforce-test/lib/python3.10/functools.py", line 61, in update_wrapper
    wrapper.__wrapped__ = wrapped
AttributeError: readonly attribute
```

Topic: sf-new-symbol-wraps
Reviewers: bradley,nathan,ryan-b,hayk
GitOrigin-RevId: 46f3be1b9e56db9b3fa6e4da0ed66af75a5ed60f