[SymForce] dev_requirements.txt errors on py < 3.8
This means you'll get an error if you follow the "CMake build" steps in
the README.  Other flows hit the `python_requires` in our `setup.py`,
which will similarly alert the user.

Error looks like this:

```
$ pip install -r dev_requirements.txt
Looking in indexes: https://pypi.python.org/simple
Processing ./third_party/skymarshal
  Preparing metadata (setup.py) ... done
Processing ./gen/python
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement symforce_requires_python_38_or_higher___your_python_version_is_incompatible (from versions: none)
ERROR: No matching distribution found for symforce_requires_python_38_or_higher___your_python_version_is_incompatible
```

There's no way to specify a "required python version" in a requirements
file, so we use this hack instead (see [the docs](https://pip.pypa.io/en/latest/reference/requirements-file-format/#requirements-file-format)).

An alternative to this would be never doing `pip install -r
dev_requirements.txt` directly, and creating some script or build rule
that does this - it's much simpler imo to bake the requirement in here,
rather than introducing additional paths to install requirements.

Reviewers: hayk,bradley,nathan,roy-v
Topic: sym-req-38
Relative: sym-isort
GitOrigin-RevId: 98bc09a9c9eb27472f389a78f3ce7bd70fea7131