[SymForce] No fast-math on Clang 7
I'm only setting this in CI - I considered having symforce not default
to adding -ffast-math on clang < 10, but I think I'd rather not special
case that. Just means that if you're a user building symforce on clang <
10 you need to realize this is the problem and set SYMFORCE_NO_FAST_MATH

Without this, you get this:

```
[ 78%] Linking CXX executable ../../bin/benchmarks/matrix_multiplication_benchmark_b1_ss
/usr/bin/ld: ../../libsymforce_gen.so: undefined reference to `__pow_finite'
/usr/bin/ld: ../../libsymforce_gen.so: undefined reference to `__powf_finite'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

See here: https://stackoverflow.com/a/74083393

Topic: sf-ci-clang-7
Reviewers: brad,nathan,ryan-b
GitOrigin-RevId: 91576f0fccb831352d94ef781a22b9af6c540a86