[SymForce] Make Ops.Registration meaningful
As it stands, one can call
`LieGroupOps.implementation(SphericalCameraCal)`
even though `SphericalCameraCal` doesn't implement `LieGroupOps` (only `StorageOps`) and, for example,
`LieGroupOps.to_tangent`
will throw if called on one of its instances.

What this pull request seeks to do is improve the error messages, encourage clearer code, and allow `Ops` to better handle multiple inheritance (it didn't require much work to do on top of everything else, so I figured why not).

For example, now if you attempt to call `LieGroupOps.to_tangent(SphericalCameraCal([2, 4], [1, 2]))`, you'll get the error message
`NotImplementedError: While <class 'symforce.cam.spherical_camera_cal.SphericalCameraCal'> is registered under StorageOps (via base class <class 'symforce.ops.interfaces.storage.Storage'>), that does not subclass LieGroupOps.'

which I think is more helpful than the old error message of

`AttributeError: type object 'ClassStorageOps' has no attribute 'to_tangent'`

Another significant change is that now in order to use a `LieGroupOps` (or any other `Ops` subclass) method on an instance of a class, the class (or one of it's base classes) must have be registered with `LieGroupOps`, meaning we'd call something like `LieGroupOps.register(TheClass, Impl)`) as opposed to just any old subclass of `Ops` (for example, `Ops.register(TheClass, Impl)` will no longer be useful, and `StorageOps.register(Matrix, ClassLieGroup)` would allow one to call `StorageOps` methods on `Matrix`, but not `LieGroupOps` methods).