Added clearer error message for dynamically created dataclasses stored in Values objects
Dynamically created dataclasses are not allowed in the index of a Values object, but the current exception thrown is very cryptic (`AttributeError: 'function' object has no attribute '<locals>'`). Minimum example demonstrating the error is given below; no exception is thrown for the first call to `from_storage_index`, but the second call gives an error because `MyDynamicDataclass` is created in a function.

```
from symforce.values import Values
from dataclasses import dataclass
from symforce import typing as T

@dataclass
class MyDataclass:
    x: T.Scalar

values = Values(data=MyDataclass(x=0,))

values.from_storage_index(values.to_storage(), values.index())

def test_assert():
    @dataclass
    class MyDynamicDataclass:
        x: T.Scalar

    values = Values(data=MyDynamicDataclass(x=0,))
    values.from_storage_index(values.to_storage(), values.index())

test_assert()
```

GitOrigin-RevId: 59c7c644b5ef351cf7cd2aceb39d41bb6a59c66f